FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json /app/

RUN apk add --no-cache curl

RUN npm install --production

COPY public /app/public
COPY src /app/src

RUN npm run build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]
