services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: valdivian_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: valdivian
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: valdivian_frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/"
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: valdivian_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/api/products"
      interval: 10s
      retries: 10

volumes:
  db_data:
