services:
  db:
    image: database:latest
    container_name: valdivian_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: valdivian
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5

  frontend:
    image: frontend:latest
    container_name: valdivian_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend:latest
    container_name: valdivian_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
